load("@rules_java//java:java_library.bzl", "java_library")
load("@rules_kotlin//kotlin:jvm.bzl", "kt_jvm_binary")

java_library(
  name = "big",
  srcs = glob(["**/Large*.java"]),
)

java_library(
  name = "small",
  srcs = glob(["**/Nu*.java"]),
)
