# java_binary(
#   name = "numberer.NumberPrinter2",
#   srcs = ["NumberPrinter.java"],
#   main_class = "src.NumberPrinter"
# )
#
# java_binary(
#   name = "src",
#   srcs = ["NumberPrinter.java"],
#   main_class = "src.NumberPrinter"
# )
